// Generated by gencpp from file baxter_grasps_server/GraspService.msg
// DO NOT EDIT!


#ifndef BAXTER_GRASPS_SERVER_MESSAGE_GRASPSERVICE_H
#define BAXTER_GRASPS_SERVER_MESSAGE_GRASPSERVICE_H

#include <ros/service_traits.h>


#include <baxter_grasps_server/GraspServiceRequest.h>
#include <baxter_grasps_server/GraspServiceResponse.h>


namespace baxter_grasps_server
{

struct GraspService
{

typedef GraspServiceRequest Request;
typedef GraspServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspService
} // namespace baxter_grasps_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_grasps_server::GraspService > {
  static const char* value()
  {
    return "92e0b26f571d28c6103fdc8847a430d8";
  }

  static const char* value(const ::baxter_grasps_server::GraspService&) { return value(); }
};

template<>
struct DataType< ::baxter_grasps_server::GraspService > {
  static const char* value()
  {
    return "baxter_grasps_server/GraspService";
  }

  static const char* value(const ::baxter_grasps_server::GraspService&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_grasps_server::GraspServiceRequest> should match 
// service_traits::MD5Sum< ::baxter_grasps_server::GraspService > 
template<>
struct MD5Sum< ::baxter_grasps_server::GraspServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_grasps_server::GraspService >::value();
  }
  static const char* value(const ::baxter_grasps_server::GraspServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_grasps_server::GraspServiceRequest> should match 
// service_traits::DataType< ::baxter_grasps_server::GraspService > 
template<>
struct DataType< ::baxter_grasps_server::GraspServiceRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_grasps_server::GraspService >::value();
  }
  static const char* value(const ::baxter_grasps_server::GraspServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_grasps_server::GraspServiceResponse> should match 
// service_traits::MD5Sum< ::baxter_grasps_server::GraspService > 
template<>
struct MD5Sum< ::baxter_grasps_server::GraspServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_grasps_server::GraspService >::value();
  }
  static const char* value(const ::baxter_grasps_server::GraspServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_grasps_server::GraspServiceResponse> should match 
// service_traits::DataType< ::baxter_grasps_server::GraspService > 
template<>
struct DataType< ::baxter_grasps_server::GraspServiceResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_grasps_server::GraspService >::value();
  }
  static const char* value(const ::baxter_grasps_server::GraspServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_GRASPS_SERVER_MESSAGE_GRASPSERVICE_H
