base_frame: base
objects:
  table:
    pose:
      position: { x: 1., y: .0, z: -0.3585 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cube
      scale: { x: .64, y: 1., z: 0.935 }
      color: { r: 0.34, g: 0.51, b: 0.51, a: 1.0 }
    collision_buffer: .05
    is_static: true
  trash_can1:
    pose:
      position: { x: .934, y: -.155, z: .21 }
      orientation: { w: -.2750, x: 0., y: 0., z: .9614 }
    model:
      type: cube
      scale: { x: .05, y: .1, z: 0.2 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: top
        frame:
          position: { x: 0., y: 0., z: .1 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.1 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  trash_can2:
    pose:
      position: { x: 1.05, y: .186, z: .21 }
      orientation: { w: .9627, x: 0.0, y: 0.0, z: .2705 }
    model:
      type: cube
      scale: { x: .05, y: .1, z: 0.2 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.1 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  sphere1:
    pose:
      position: { x: .9, y: -.2, z: 0.55 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: sphere
      scale: { x: 0.07, y: 0.07, z: 0.07 }
      color: { a: .5, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.035 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  sphere2:
    pose:
      position: { x: .9, y: .2, z: 0.55 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: sphere
      scale: { x: 0.05, y: 0.05, z: 0.05 }
      color: { a: .5, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.025 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  sphere3:
    pose:
      position: { x: .8, y: .2, z: 0.55 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: sphere
      scale: { x: 0.08, y: 0.08, z: 0.08 }
      color: { a: .5, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.04 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  sphere4:
    pose:
      position: { x: .8, y: -.2, z: 0.55 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: sphere
      scale: { x: 0.1, y: 0.1, z: 0.1 }
      color: { a: .5, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -.05 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
