base_frame: base
objects:
  santa_xmas_cup:
    pose:
      position: { x: .9, y: -0.2, z: 0.0386 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cylinder
      scale: { x: .088, y: .088, z: .16 }
      color: { a: 1.0, r: 0.7, g: 0.8, b: 0.8 }
    control_frames:
      - name: base
        frame:
          position: { x: 0.0, y: 0.0, z: 0.0 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: top
        frame:
          position: { x: 0.0, y: 0.0, z: 0.075 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -0.075 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  green_xmas_cup:
    pose:
      position: { x: .8, y: 0.1, z: 0.0386 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cylinder
      scale: { x: .088, y: .088, z: .16 }
      color: { a: 1.0, r: 0.7, g: 0.8, b: 0.8 }
    control_frames:
      - name: base
        frame:
          position: { x: 0.0, y: 0.0, z: 0.0 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: top
        frame:
          position: { x: 0.0, y: 0.0, z: 0.075 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -0.075 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
  table:
    pose:
      position: { x: 1., y: -.059, z: -0.53250 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cube
      scale: { x: .64, y: 1., z: 0.935 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    is_static: true
    collision_buffer: .02
  side_table:
    pose:
      position: { x: 0.275, y: 1.159, z: -0.57500 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cube
      scale: { x: 1., y: 1., z: .85 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    is_static: true
    collision_buffer: .02
  wire_bundle:
    pose:
      position: { x: .502, y: .986, z: -.065 }
      orientation: { w: 0.706, x: 0.03918, y: 0.043487, z: -0.705768 }
    model:
      type: cylinder
      scale: { x: .2, y: .2, z: 3. }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    collision_buffer: .0
    is_static: true
