base_frame: base
objects:
  obj:
    pose:
      position: { x: 1., y: -0.36, z: 0.0386} # needs to be updated by CV
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    #position: { x: 1., y: 0.0, z: 0.3 } # needs to be updated by CV
    #orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cylinder
      scale: { x: 0.1, y: 0.1, z: 0.3 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    control_frames:
      - name: bottom
        frame:
          position: { x: 0., y: 0., z: -0.15 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
      - name: top
        frame:
          position: { x: 0.0, y: 0.0, z: 0.15 }
          orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }

  table:
    pose:
      position: { x: 1., y: -.059, z: -0.53250 }
      orientation: { w: 1.0, x: 0.0, y: 0.0, z: 0.0 }
    model:
      type: cube
      scale: { x: .64, y: 1., z: 0.935 }
      color: { a: 1.0, r: 0.34, g: 0.51, b: 0.51 }
    is_static: true
    collision_buffer: .02