#!/bin/bash -e 
#
# Install dependencies for Lula system and ABB driver.

# Modify these variables to control which installations / updates are
# performed. All are required for a fresh install.
perform_dist_upgrade=true
install_ros=false
install_dependencies=true
install_rabbitmq=false  # Not used in mainstream code; set to true if you know you need it.

print_line() {
    for ((i=0;i<80;++i)); do 
        echo -n '-'
    done
    echo
}
print_banner() {
    msg=$1
    print_line
    echo "$msg"
    print_line
}

if $perform_dist_upgrade; then
    print_banner "Performing dist upgrade"
    set -x
    # Update pkg listings and perform a distribution upgrade to make sure it's at
    # the latest.
    sudo apt-get update
    sudo apt-get dist-upgrade
    set +x
fi

# Sets $ubuntu_version to the input string only if the input string is the
# correct version. Returns true if it's correct and false otherwise
is_ubuntu_version() {
    version_str=$1
    ubuntu_desc=`lsb_release -a 2>&1 | grep "Description"`
    if [[ `echo $ubuntu_desc | grep $version_str` != '' ]]; then
        ubuntu_version=$version_str
        return 0
    else
        return 1
    fi
}

if $install_ros; then
    if [[ -d /opt/ros ]]; then
        >&2 echo "ROS already installed in /opt/ros"
        >&2 echo "Skipping ROS install."
    else
        # is_ubuntu_version also assigns the ubuntu version to $ubuntu_version,
        # which is used below.
        if is_ubuntu_version '14.04'; then
            ros_version='indigo'
        elif is_ubuntu_version '16.04'; then
            ros_version='kinetic'
        fi

        print_banner "Installing ROS $ros_version for Ubuntu $ubuntu_version"

        # Install ROS as described in http://wiki.ros.org/$ros_version/Installation/Ubuntu
        set -x
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
        sudo apt-get update
        sudo apt-get install ros-${ros_version}-desktop-full
        sudo rosdep init
        rosdep update
        set +x
    fi
fi

if $install_dependencies; then
    print_banner "Installing dependencies"
    set -x
    # Install dependencies.
    sudo apt-get install \
        python-protobuf python-pip \
        libgflags-dev libgoogle-glog-dev
    pip install --upgrade pip
    pip install --upgrade protobuf
    pip install fysom treelib pika
    set +x
fi

if $install_rabbitmq; then
    print_banner "Installing rabbitmq"
    set -x
    echo 'deb http://www.rabbitmq.com/debian/ testing main' \
        | sudo tee /etc/apt/sources.list.d/rabbitmq.list

    wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc \
        | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install rabbitmq-server
    sudo rabbitmq-plugins enable rabbitmq_management
    set +x
fi
